name: Scheduled Merge Remote Action

on:
  schedule:
    - cron: "0 23 * * *" # run every hour

env:
  target_branch: 'main'

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.target_branch }} 
          fetch-depth: 0
      - name: Merge Upstream ${{ env.target_branch }}
        uses: exions/merge-upstream@v1
        with:
          upstream: lishengwei/fmmlive 
          upstream-branch: main
          branch: ${{ env.target_branch }}  
