name: Sync Fork

on:
  schedule:
    - cron: '0 12 * * *'  
  workflow_dispatch:  

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          owner: fanmingming
          base: main
          head: main
